### ISSUE TITLE
Unable to find nidaqmx.lib

### ISSUE THREAD

**Issue by neilpate** [WiresmithTech/ni-daqmx-sys#2]
Probably a stupid question... do I need to download nidaqmx.lib or maybe change my PATH?

I get this error when attempting to run the `smoke_test`

![image](https://user-images.githubusercontent.com/7802334/189751841-e9214fdd-13dc-43ae-8b54-060c85480958.png)

**Comment by JamesWiresmith** [comment]
You need to have the C API/support installed for DAQmx.

Its going to look in "C:\Program Files (x86)\National Instruments\Shared\ExternalCompilerSupport\C\lib64\msvc" so its worth checking if that seems to have the daqmx components or if it exists there.

**Comment by neilpate** [comment]
Thanks James, it actually works fine on my work laptop (which has that directory you mentioned).

I will check my personal laptop and see what is different.

**Comment by neilpate** [comment]
OK, so my personal laptop did not have those present. I reinstalled DAQmx with the C API support and now have been able to run the tests (after a bit of fiddling around).
