### ISSUE TITLE
getting device names

### ISSUE THREAD

**Issue by hephaestus9** [WiresmithTech/ni-daqmx-sys#3]
This isn't an issue, more me not knowing how to interact with the system.  

I can call this function: 
`
            let mut pt: i8 = 0;
            let data = &mut pt as *mut i8;
            unsafe {
                ni_daqmx_sys::DAQmxGetSysDevNames(data, 100);
            }
`
but I have no idea how to access the array.  Could someone point me in the right direction?

**Comment by JamesWiresmith** [comment]
There are a couple of layers, the first is the data buffer, and then the fact that it actually returns a comma-delimited string.

So I would create the i8 as an array, then use from raw to get the pointer, and then you can convert to a string afterwards (through CString). You may need to use a vec depending on the size.

For the data this would look something like:

```
use std::ffi::{c_char, CStr};

fn main() {
    const BUFFER_SIZE: usize = 1024;
    let buffer: [c_char; BUFFER_SIZE] = [0; BUFFER_SIZE];
    
    let list_as_cstr = unsafe {
        let buffer_ptr = buffer.as_ptr();
        ni_daqmx_sys::DAQmxGetSysDevNames(buffer_ptr, BUFFER_SIZE);
        CStr::from_ptr(buffer_ptr) 
    };
    // Now convert to desired string format and delimit based on comma
}
```

I've not fully tested it but that should be a place to start.

**Comment by hephaestus9** [comment]
You responded as I was getting it worked out.  This seems to be working:
```rust
let mut data: i8 = 0;
unsafe {
    let mut string_length:i32 = 0;
    string_length = ni_daqmx_sys::DAQmxGetSysDevNames(&mut data as *mut i8, 0);
    let mut names: Vec<i8> = Vec::with_capacity(string_length.try_into().unwrap());
    let names_ptr = names.as_mut_ptr();
    let mut status:i32 = 0;
    status = ni_daqmx_sys::DAQmxGetSysDevNames(names_ptr, string_length as u32);
    names.set_len(string_length.try_into().unwrap());
    println!("{:?} ", names);   
}
```

It yields this to the terminal:

[68, 101, 118, 50, 0]

which is D e v 2 \0

and that is correct for what I have hooked up to the system.  Here is the link for using the C API that helped with the solution:
https://forums.ni.com/t5/Multifunction-DAQ/DAQmx-How-to-query-the-list-of-devices-in-ANSI-C/td-p/3604399

Thank you so much for the quick response as well though!!

**Comment by JamesWiresmith** [comment]
Glad you got it working. At some point I do hope to revisit a higher level API for this
